
services:
   api:

    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_API}
    ports:
     - "0.0.0.0:4000:4000"
    volumes:
     - .:/usr/src/app
     - root_node_modules:/usr/src/app/node_modules
     - api_node_modules:/usr/src/app/apps/api/node_modules
     - api_prisma_generated:/usr/src/app/apps/api/src/generated
   

volumes:
  root_node_modules: 
  api_node_modules:
  api_prisma_generated:
    
    

